# Site settings
title: 心有多远，路就有多远。
name: PHoneIX
email: me@halo9pan.info
description: > # this means to ignore newlines until "baseurl:"
  代码工匠，数据画家，魔云散人，全栈程序员，交互设计师，智能实践者……
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.halo9pan.info" # the base hostname & protocol for your site
twitter_username: Halo9Pan
github_username:  Halo9Pan

# Build settings
markdown: kramdown
